# Generated by Django 5.1.4 on 2025-01-29 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_response', models.CharField(default='DEFAULT_CODE', max_length=10, unique=True)),
                ('message', models.TextField(default='Default message')),
            ],
        ),
        migrations.CreateModel(
            name='USSDMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('output', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='automatisation.ussdmenu')),
                ('server_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatisation.serverresponse')),
            ],
        ),
    ]
