# Generated by Django 5.1.4 on 2025-02-06 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalUSSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ussdmenu',
            name='server_response',
        ),
        migrations.RemoveField(
            model_name='ussdmenu',
            name='parent',
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('entree', models.CharField(max_length=255)),
                ('sortie_attendue', models.TextField()),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatisation.canalussd')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_test', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('OK', 'OK'), ('NOK', 'NOK')], max_length=10)),
                ('message_erreur', models.TextField(blank=True, null=True)),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatisation.usecase')),
            ],
        ),
        migrations.DeleteModel(
            name='ServerResponse',
        ),
        migrations.DeleteModel(
            name='USSDMenu',
        ),
    ]
