# Generated by Django 5.1.4 on 2025-02-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatisation', '0002_canalussd_remove_ussdmenu_server_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='numerousecase',
            field=models.IntegerField(default=0),
        ),
    ]
