# Generated by Django 5.1.6 on 2025-02-11 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatisation', '0004_usecase_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('description', models.TextField()),
                ('input_value', models.CharField(max_length=255)),
                ('expected_output', models.TextField()),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatisation.usecase')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='DetailedTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telephone', models.CharField(max_length=20)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('OK', 'OK'), ('NOK', 'NOK')], max_length=10)),
                ('message_erreur', models.TextField(blank=True, null=True)),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatisation.testresult')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatisation.teststep')),
            ],
            options={
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='AlertConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatisation.usecase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'use_case', 'email')},
            },
        ),
    ]
